services:
  bot:
    image: ${BOT_IMAGE:-ghcr.io/hoomanjcode/telegram-7z-bot:latest}
    container_name: telegram-7z-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
      - ./data:/app/data
    networks:
      - caddy

networks:
  caddy:
    external: true
